### ISSUE TITLE
Version 1.2.1 does not run - ImportError: cannot import name 'rockstar'

### ISSUE THREAD

**Issue by asilano** [yanorestes/rockstar-py#7]
After a fresh install of Python 3.4 via package manager (onto CentOS 7), followed by pip3 and `sudo pip3 install rockstar-py`, running `rockstar-py` gives the following error:

```
[vagrant@adpc-com-039 Python-3.7.0]$ rockstar-py
Traceback (most recent call last):
  File "/usr/bin/rockstar-py", line 9, in <module>
    load_entry_point('rockstar-py==1.2.1', 'console_scripts', 'rockstar-py')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2719, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2379, in load
    return self.resolve()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2385, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.4/site-packages/rockstarpy/__init__.py", line 1, in <module>
    from . import rockstar
  File "/usr/lib/python3.4/site-packages/rockstarpy/rockstar.py", line 2, in <module>
    from . import command_line
  File "/usr/lib/python3.4/site-packages/rockstarpy/command_line.py", line 2, in <module>
    from . import rockstar
ImportError: cannot import name 'rockstar'
```

**Comment by jmsv** [comment]
I think the import change causing this was introduced here: https://docs.python.org/3/whatsnew/3.5.html#other-language-changes

> Circular imports involving relative imports are now supported. (Contributed by Brett Cannon and Antoine Pitrou in bpo-17636.)

**Comment by asilano** [comment]
Cool, sounds good. I look forward to giving it a go.

**Comment by yanorestes** [comment]
It should work fine now, thanks to @jmsv!
